config/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from app.views import *
from app.views import EditarLivroView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('livros/', LivrosView.as_view(), name='livros'),
    #path('reserva/', EmprestimoView.as_view(), name='reserva'),
    path('cidade/', CidadesView.as_view(), name='cidade'),
    path('autor/', AutoresView.as_view(), name='autor'),
    path('editor/', EditorasView.as_view(), name='editora'),
    path('leitor/', LeitoresView.as_view(), name='leitor'),
    path('genero/', GenerosView.as_view(), name='genero'),
    path('admin/', admin.site.urls),
    path('delete/<int:id>/', DeleteLivroView.as_view(), name = 'delete'),
    path('editar/<int:id>/', EditarLivroView.as_view(), name='editar')
]

app/models.py
from django.db import models

class Cidade(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome da cidade")
    uf = models.CharField(max_length=2, verbose_name="UF")

    def __str__(self):
        return f"{self.nome}, {self.uf}"

    class Meta:
        verbose_name = "Cidade"
        verbose_name_plural = "Cidades"

class Autor(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome do autor")
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE, verbose_name="Cidade do autor")

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Autor"
        verbose_name_plural = "Autores"

class Editora(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome da editora")
    site = models.CharField(max_length=100, verbose_name="Site da editora")
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE, verbose_name="Cidade da editora")

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Editora"
        verbose_name_plural = "Editoras"

class Leitor(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome do leitor")
    email = models.CharField(max_length=100, verbose_name="Email do leitor")
    cpf = models.CharField(max_length=11, unique=True, verbose_name="CPF do leitor")

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Leitor"
        verbose_name_plural = "Leitores"

class Genero(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Gênero")

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Gênero"
        verbose_name_plural = "Gêneros"

class Livro(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome do livro")
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE, verbose_name="Autor do livro")
    editora = models.ForeignKey(Editora, on_delete=models.CASCADE, verbose_name="Editora do livro")
    genero = models.ForeignKey(Genero, on_delete=models.CASCADE, verbose_name="Gênero do livro")
    preco = models.IntegerField(verbose_name="Preço do livro")
    data_plub = models.DateField(verbose_name="Data de publicação do livro")
    status = models.BooleanField(verbose_name="Status do livro")

    def __str__(self):
        return f'{self.nome}, {self.autor}'

    class Meta:
        verbose_name = "Livro"
        verbose_name_plural = "Livros"

app/forms.py
from django import forms
from .models import Livro

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = '__all__'

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(LivroForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'titulo',
            'autor',
            'editora',
            'genero',
            'preco',
            'data_pub',
            'status',
            Submit('submit', 'Salvar')
        )

app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib import messages
from django.urls import reverse
from .models import *
from .forms import LivroForm  # certifique-se que existe esse form

class IndexView(View):
    def get(self, request, *args, **kwargs):
        livros = Livro.objects.all()
        return render(request, 'index.html',{'livros': livros})

class LivrosView(View):
    def get(self, request, *args, **kwargs):
        livros = Livro.objects.all()
        return render(request, 'livros.html', {'livros': livros})

class CidadesView(View):
    def get(self, request, *args, **kwargs):
        cidades = Cidade.objects.all()
        return render(request, 'cidade.html', {'cidades': cidades})

class AutoresView(View):
    def get(self, request, *args, **kwargs):
        autores = Autor.objects.all()
        return render(request, 'autor.html', {'autores': autores})

class EditorasView(View):
    def get(self, request, *args, **kwargs):
        editoras = Editora.objects.all()
        return render(request, 'editora.html', {'editoras': editoras})

class LeitoresView(View):
    def get(self, request, *args, **kwargs):
        leitores = Leitor.objects.all()
        return render(request, 'leitor.html', {'leitores': leitores})

class GenerosView(View):
    def get(self, request, *args, **kwargs):
        generos = Genero.objects.all()
        return render(request, 'genero.html', {'generos': generos})

class DeleteLivroView(View):
    def get(self, request, id, *args, **kwargs):
        livro = get_object_or_404(Livro, id=id)
        livro.delete()
        messages.success(request, 'Livro excluído com sucesso!')
        return redirect('livros')

class EditarLivroView(View):
    template_name = 'editar_livro.html'

    def get(self, request, id, *args, **kwargs):
        livro = get_object_or_404(Livro, id=id)
        form = LivroForm(instance=livro)
        return render(request, self.template_name, {'livro': livro, 'form': form})

    def post(self, request, id, *args, **kwargs):
        livro = get_object_or_404(Livro, id=id)
        form = LivroForm(request.POST, instance=livro)
        if form.is_valid():
            form.save()
            messages.success(request, 'As edições foram salvas com sucesso!')
            return redirect(reverse('editar', kwargs={'id': id}))
        else:
            messages.error(request, 'Corrija os erros no formulário antes de enviar novamente.')
            return render(request, self.template_name, {'livro': livro, 'form': form})

app/templates/autor.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autores</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="/">Biblioteca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link text-dark" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/livros/">Livros</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/reserva/">Reserva</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/cidade/">Cidade</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/autor/">Autor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/editor/">Editora</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/genero/">Genero</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/leitor/">Leitor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/admin/">Administração</a></li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <h2 class="mb-4">Tabela de Autores</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Cidade</th>
                    <th scope="col">Livros Associados</th>
                </tr>
            </thead>
            <tbody>
                {% for autor in autores %}
                <tr>
                    <td>{{ autor.nome }}</td>
                    <td>{{ autor.cidade.nome }}</td>
                    <td>
                        <ul>
                            {% for livro in autor.livro_set.all %}
                            <li>{{ livro.nome }}</li>
                            {% empty %}
                            <li>Sem livros cadastrados</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

app/templates/cidade.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cidades</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="/">Biblioteca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link text-dark" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/livros/">Livros</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/reserva/">Reserva</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/cidade/">Cidade</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/autor/">Autor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/editor/">Editora</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/genero/">Genero</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/leitor/">Leitor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/admin/">Administração</a></li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        <h2 class="mb-4">Tabela de Cidades</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>UF</th>
                </tr>
            </thead>
            <tbody>
                {% for cidade in cidades %}
                <tr>
                    <td>{{ cidade.nome }}</td>
                    <td>{{ cidade.uf }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- scripts iguais -->
</body>

</html>

app/templates/editarlivros.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhes e Edição do Livro</title>
    <!-- Incluindo Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Estilos personalizados (se houver) -->
</head>
<body>
    <div class="container mt-5">
        <a href="/" class="btn btn-warning">Voltar para a Home</a>
        
        <h2>Detalhes do Livro: {{ livro.nome }}</h2>
        <p>Nome: {{ livro.nome }}</p>
        <p>Autor: {{ livro.autor }}</p>
        <p>Editora: {{ livro.editora }}</p>
        <p>Gênero: 
            {% for genero in livro.genero.all %}
                {{ genero.nome }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p>Preço: R$ {{ livro.preco }}</p>
        <p>Data de Publicação: {{ livro.data_plub }}</p>
        <p>Status: {{ livro.status }}</p>

        <h3 class="mt-4">Editar Livro</h3>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %}class="{{ message.tags }}"{% endif %} style="color: red;">
                        <b>{{ message }}</b>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success btn-block btn-lg mt-2">Salvar Edições do Livro</button>
        </form>
        <br>
    </div>

    <!-- Incluindo jQuery e Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/editora.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editoras</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="/">Biblioteca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link text-dark" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/livros/">Livros</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/reserva/">Reserva</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/cidade/">Cidade</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/autor/">Autor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/editor/">Editora</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/genero/">Genero</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/leitor/">Leitor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/admin/">Administração</a></li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <h2 class="mb-4">Tabela de Editoras</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Link</th>
                    <th scope="col">Cidade</th>
                </tr>
            </thead>
            <tbody>
                {% for editora in editoras %}
                <tr>
                    <td>{{ editora.nome }}</td>
                    <td>{{ editora.site }}</a></td>
                    <td>{{ editora.cidade }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

app/templates/genero.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gêneros</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="/">Biblioteca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link text-dark" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/livros/">Livros</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/reserva/">Reserva</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/cidade/">Cidade</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/autor/">Autor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/editor/">Editora</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/genero/">Genero</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/leitor/">Leitor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/admin/">Administração</a></li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <h2 class="mb-4">Tabela de Gêneros</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Gênero</th>
                    <th scope="col">Livros Associados</th>
                </tr>
            </thead>
            <tbody>
                {% for genero in generos %}
                <tr>
                    <td>{{ genero.nome }}</td>
                    <td>
                        <ul>
                            {% for livro in genero.livro_set.all %}
                            <li>{{ livro.nome }}</li>
                            {% empty %}
                            <li>Sem livros cadastrados</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="/">Biblioteca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/livros/">Livros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/reserva/">Reserva</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/cidade/">Cidade</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/autor/">Autor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/editor/">Editora</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/genero/">Genero</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/leitor/">Leitor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="/admin/">Administração</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        <div class="jumbotron text-center">
            <h1 class="display-4">Olá, é bom te ver por aqui</h1>
            <p class="lead">Esta é a página inicial da Biblioteca</p>
            <p class="lead">Seja Bem Vindo(A)</p>
        </div>
    </div>
    <!-- Incluindo jQuery e Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Autor</th>
                <th scope="col">Editora</th>
                <th scope="col">Gênero</th>
                <th scope="col">Preço</th>
                <th scope="col">Data Publicação</th>
                <th scope="col">Status</th>
                <th scope="col">Excluir</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1984</td>
                <td>George Orwell</td>
                <td>Companhia das Letras</td>
                <td>Ficção</td>
                <td>R$ 39,90</td>
                <td>08/06/1949</td>
                <td>Disponível</td>
                <td><button class="btn btn-danger btn-sm">Excluir</button></td>
            </tr>
        </tbody>
    </table>
    
    
</body>

</html>

app/templates/leitor.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Leitores</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <a class="navbar-brand" href="/">Biblioteca</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link text-dark" href="/">Home</a></li>
        <li class="nav-item"><a class="nav-link text-dark" href="/livros/">Livros</a></li>
        <li class="nav-item"><a class="nav-link text-dark" href="/reserva/">Reserva</a></li>
        <li class="nav-item"><a class="nav-link text-dark" href="/cidade/">Cidade</a></li>
        <li class="nav-item"><a class="nav-link text-dark" href="/autor/">Autor</a></li>
        <li class="nav-item"><a class="nav-link text-dark" href="/editor/">Editora</a></li>
        <li class="nav-item"><a class="nav-link text-dark" href="/genero/">Genero</a></li>
        <li class="nav-item"><a class="nav-link text-dark" href="/leitor/">Leitor</a></li>
        <li class="nav-item"><a class="nav-link text-dark" href="/admin/">Administração</a></li>
      </ul>
    </div>
  </nav>

  <div class="container mt-5">
    <h2 class="mb-4">Tabela de Leitores</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Email</th> 
          <th scope="col">Livros Reservados</th>
        </tr>
      </thead>
      <tbody>
        {% for leitor in leitores %}
        <tr>
          <td>{{ leitor.nome }}</td>
          <td>{{ leitor.email }}</td>
          <td>
            <ul>
              {% for reserva in leitor.emprestimo_set.all %}
              <li>{{ reserva.livro.nome }}</li>
              {% empty %}
              <li>Nenhum livro reservado</li>
              {% endfor %}
            </ul>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

app/templates/livros.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Inicial</title>
    <!-- Incluindo Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="/">Biblioteca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link text-dark" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/livros/">Livros</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/reserva/">Reserva</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/cidade/">Cidade</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/autor/">Autor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/editor/">Editora</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/genero/">Genero</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/leitor/">Leitor</a></li>
                <li class="nav-item"><a class="nav-link text-dark" href="/admin/">Administração</a></li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        <h2 class="mb-4">Tabela de Livros</h2>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Autor</th>
                    <th scope="col">Editora</th>
                    <th scope="col">Gênero</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Data Publicação</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for livros in livros %}
                <tr>
                    <td>{{ livros.nome }}</td>
                    <td>{{ livros.autor }}</td>
                    <td>{{ livros.editora }}</td>
                    <td>{{ livros.genero }}</td>
                    <td>{{ livros.preco }}</td>
                    <td>{{ livros.data_plub }}</td>
                    <td>{{ livros.status }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Incluindo jQuery e Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>